apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediawiki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mediawiki.fullname" . }}
    helm.sh/chart: {{ include "mediawiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)))}}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
  {{- if .Values.service.httpsPort }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.https)))}}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "mediawiki.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
